apiVersion: v1
data:
  password: ZWNvbXBhc3N3b3Jk
  rootpassword: ZWNvbXJvb3RwYXNzd29yZA==
  username: ZWNvbXVzZXI=
kind: Secret
metadata:
  creationTimestamp: "2026-07-02T18:20:33Z"
  name: db-credentials  
type: Opaque
