apiVersion: v1
data:
  DB_HOST: "mysql-service.ecomwebapp.svc.cluster.local"
  DB_NAME: "ecomdb"
  FEATURE_DARK_MODE: "true"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app-config
  namespace: ecomwebapp
