apiVersion: v1
kind: PersistentVolume
metadata:
  name: cicd-test-mysql-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/cicd-test-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cicd-test-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: cicd-test-mysql-pv
  resources:
    requests:
      storage: 2Gi