apiVersion: v1
data:
  password: ZWNvbXBhc3N3b3Jk
  rootpassword: ZWNvbXJvb3RwYXNzd29yZA==
  username: ZWNvbXVzZXI=
kind: Secret
metadata:
  creationTimestamp: "2026-07-02T18:20:33Z"
  name: db-credentials
  namespace: ecomwebapp
  resourceVersion: "10386785"
  uid: a2e9b577-d67a-482f-ae9b-2a8b22dd48d6
type: Opaque
