apiVersion: v1
data:
  db-load-script.sql: |
    CREATE DATABASE IF NOT EXISTS ecomdb;
        USE ecomdb;

        CREATE TABLE IF NOT EXISTS Products (
        id MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
        Name VARCHAR(255) DEFAULT NULL,
        Price VARCHAR(255) DEFAULT NULL,
        ImageUrl VARCHAR(255) DEFAULT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_products_name_imageurl (Name, ImageUrl)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

        INSERT INTO Products (Name, Price, ImageUrl)
        VALUES
        ('Laptop', '100', 'c-1.png'),
        ('Drone', '200', 'c-2.png'),
        ('VR', '300', 'c-3.png'),
        ('Tablet', '50', 'c-5.png'),
        ('Watch', '90', 'c-6.png'),
        ('Phone Covers', '20', 'c-7.png'),
        ('Phone', '80', 'c-8.png'),
        ('Laptop', '150', 'c-4.png')
        ON DUPLICATE KEY UPDATE
        Price = VALUES(Price),
        ImageUrl = VALUES(ImageUrl);
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-init-cm
  namespace: ecomwebapp
